/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as StoreRouteImport } from './routes/_store'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StoreIndexRouteImport } from './routes/_store/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminRestoreRouteImport } from './routes/admin/restore'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminMarketingRouteImport } from './routes/admin/marketing'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminBannersRouteImport } from './routes/admin/banners'
import { Route as StoreWishlistRouteImport } from './routes/_store/wishlist'
import { Route as StoreThankYouRouteImport } from './routes/_store/thank-you'
import { Route as StoreShopRouteImport } from './routes/_store/shop'
import { Route as StoreCheckoutRouteImport } from './routes/_store/checkout'
import { Route as StoreCartRouteImport } from './routes/_store/cart'
import { Route as StoreAddressesRouteImport } from './routes/_store/addresses'
import { Route as StoreAccountRouteImport } from './routes/_store/account'
import { Route as StoreSplatRouteImport } from './routes/_store/$'
import { Route as StoreProductIdRouteImport } from './routes/_store/product.$id'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/_store',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRestoreRoute = AdminRestoreRouteImport.update({
  id: '/restore',
  path: '/restore',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const StoreWishlistRoute = StoreWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => StoreRoute,
} as any)
const StoreThankYouRoute = StoreThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => StoreRoute,
} as any)
const StoreShopRoute = StoreShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCheckoutRoute = StoreCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCartRoute = StoreCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => StoreRoute,
} as any)
const StoreAddressesRoute = StoreAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => StoreRoute,
} as any)
const StoreAccountRoute = StoreAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => StoreRoute,
} as any)
const StoreSplatRoute = StoreSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => StoreRoute,
} as any)
const StoreProductIdRoute = StoreProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => StoreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof StoreIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/$': typeof StoreSplatRoute
  '/account': typeof StoreAccountRoute
  '/addresses': typeof StoreAddressesRoute
  '/cart': typeof StoreCartRoute
  '/checkout': typeof StoreCheckoutRoute
  '/shop': typeof StoreShopRoute
  '/thank-you': typeof StoreThankYouRoute
  '/wishlist': typeof StoreWishlistRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/restore': typeof AdminRestoreRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/product/$id': typeof StoreProductIdRoute
}
export interface FileRoutesByTo {
  '/$': typeof StoreSplatRoute
  '/account': typeof StoreAccountRoute
  '/addresses': typeof StoreAddressesRoute
  '/cart': typeof StoreCartRoute
  '/checkout': typeof StoreCheckoutRoute
  '/shop': typeof StoreShopRoute
  '/thank-you': typeof StoreThankYouRoute
  '/wishlist': typeof StoreWishlistRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/restore': typeof AdminRestoreRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/': typeof StoreIndexRoute
  '/admin': typeof AdminIndexRoute
  '/product/$id': typeof StoreProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_store': typeof StoreRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_store/$': typeof StoreSplatRoute
  '/_store/account': typeof StoreAccountRoute
  '/_store/addresses': typeof StoreAddressesRoute
  '/_store/cart': typeof StoreCartRoute
  '/_store/checkout': typeof StoreCheckoutRoute
  '/_store/shop': typeof StoreShopRoute
  '/_store/thank-you': typeof StoreThankYouRoute
  '/_store/wishlist': typeof StoreWishlistRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/restore': typeof AdminRestoreRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/_store/': typeof StoreIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_store/product/$id': typeof StoreProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/$'
    | '/account'
    | '/addresses'
    | '/cart'
    | '/checkout'
    | '/shop'
    | '/thank-you'
    | '/wishlist'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/marketing'
    | '/admin/media'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/restore'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/account'
    | '/addresses'
    | '/cart'
    | '/checkout'
    | '/shop'
    | '/thank-you'
    | '/wishlist'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/marketing'
    | '/admin/media'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/restore'
    | '/admin/settings'
    | '/admin/users'
    | '/'
    | '/admin'
    | '/product/$id'
  id:
    | '__root__'
    | '/_store'
    | '/admin'
    | '/_store/$'
    | '/_store/account'
    | '/_store/addresses'
    | '/_store/cart'
    | '/_store/checkout'
    | '/_store/shop'
    | '/_store/thank-you'
    | '/_store/wishlist'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/marketing'
    | '/admin/media'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/restore'
    | '/admin/settings'
    | '/admin/users'
    | '/_store/'
    | '/admin/'
    | '/_store/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StoreRoute: typeof StoreRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_store': {
      id: '/_store'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_store/': {
      id: '/_store/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/restore': {
      id: '/admin/restore'
      path: '/restore'
      fullPath: '/admin/restore'
      preLoaderRoute: typeof AdminRestoreRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_store/wishlist': {
      id: '/_store/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof StoreWishlistRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/thank-you': {
      id: '/_store/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof StoreThankYouRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/shop': {
      id: '/_store/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof StoreShopRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/checkout': {
      id: '/_store/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof StoreCheckoutRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/cart': {
      id: '/_store/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof StoreCartRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/addresses': {
      id: '/_store/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof StoreAddressesRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/account': {
      id: '/_store/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof StoreAccountRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/$': {
      id: '/_store/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof StoreSplatRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/product/$id': {
      id: '/_store/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof StoreProductIdRouteImport
      parentRoute: typeof StoreRoute
    }
  }
}

interface StoreRouteChildren {
  StoreSplatRoute: typeof StoreSplatRoute
  StoreAccountRoute: typeof StoreAccountRoute
  StoreAddressesRoute: typeof StoreAddressesRoute
  StoreCartRoute: typeof StoreCartRoute
  StoreCheckoutRoute: typeof StoreCheckoutRoute
  StoreShopRoute: typeof StoreShopRoute
  StoreThankYouRoute: typeof StoreThankYouRoute
  StoreWishlistRoute: typeof StoreWishlistRoute
  StoreIndexRoute: typeof StoreIndexRoute
  StoreProductIdRoute: typeof StoreProductIdRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreSplatRoute: StoreSplatRoute,
  StoreAccountRoute: StoreAccountRoute,
  StoreAddressesRoute: StoreAddressesRoute,
  StoreCartRoute: StoreCartRoute,
  StoreCheckoutRoute: StoreCheckoutRoute,
  StoreShopRoute: StoreShopRoute,
  StoreThankYouRoute: StoreThankYouRoute,
  StoreWishlistRoute: StoreWishlistRoute,
  StoreIndexRoute: StoreIndexRoute,
  StoreProductIdRoute: StoreProductIdRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRestoreRoute: typeof AdminRestoreRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRestoreRoute: AdminRestoreRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StoreRoute: StoreRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
